# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/enc/local/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/unenc/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "rpool/enc/local/var";
      fsType = "zfs";
      neededForBoot = true;
    };

  fileSystems."/cache" =
    { device = "rpool/enc/local/cache";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/enc/safe/home";
      fsType = "zfs";
    };

  fileSystems."/mail" =
    { device = "rpool/enc/safe/home/mail";
      fsType = "zfs";
    };

  fileSystems."/persistent" =
    { device = "rpool/enc/safe/persistent";
      fsType = "zfs";
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0662-7545";
      fsType = "vfat";
    };

  swapDevices = [{ device = "/dev/sda2"; }];

}
