# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/enc/local/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DBF9-38ED";
      fsType = "vfat";
    };

  fileSystems."/cache" =
    { device = "rpool/enc/local/cache";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/unenc/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "rpool/enc/local/var";
      fsType = "zfs";
    };

  fileSystems."/persistent" =
    { device = "rpool/enc/safe/persistent";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f60f51e6-59f0-41ba-a5c8-f9bd438d2dce"; }
    ];

  hardware.enableRedistributableFirmware = true;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
