# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "pcie_aspm=off" ];
  hardware.opengl.driSupport32Bit = true;

  hardware.enableRedistributableFirmware = true;

  fileSystems."/" =
    { device = "pool/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "pool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6DA4-A592";
      fsType = "vfat";
    };

  swapDevices = [ {device="/dev/disk/by-label/swap";} ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
